version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    
  wordpress:
    image: wordpress:5.8.3-php8.1
    depends_on:
      - "db"
    volumes:
      - "wp:/var/www/html:rw"
      - "./plugins:/var/www/html/wp-content/plugins"
    ports:
      - "8008:80"
    user: "www-data"
    restart: "always"
    environment:
      WORDPRESS_DB_HOST: "192.168.10.164"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      WORDPRESS_DB_NAME: "wordpress"

  wp-cli:
    image: "wordpress:cli-php8.1"
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
      - WORDPRESS_DB_HOST=192.168.10.164
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - "db"
    volumes:
      - "wp:/var/www/html:rw"
      - "./bin/install-wp.sh:/usr/local/bin/install-wp:ro"
      - "./plugins:/var/www/html/wp-content/plugins"

volumes:
  db: {}
  wp: {}
